from sklearn.ensemble import GradientBoostingClassifier

gradient_boost = GradientBoostingClassifier(
    loss="deviance",
    learning_rate=0.1,
    n_estimators=100,
    subsample=1.0,
    criterion="friedman_mse",
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_depth=3,
    min_impurity_decrease=0.0,
    min_impurity_split=None,
    init=None,
    random_state=None,
    max_features=None,
    verbose=0,
    max_leaf_nodes=None,
    warm_start=False,
    presort="auto",
    validation_fraction=0.1,
    n_iter_no_change=None,
    tol=0.0001,
)
